flaxandteal/coral-arches

- .github/workflows/project.yml
- Dockerfile
- Dockerfile.static
- Dockerfile.static-py
I have had to use the old arches coral base for the CI to work correctly. I would like to get back and investigate the reason the 7.5 bug fix build of coral arches is throwing a database column missing error when deployed.
> Fixed issues with CI not using the active branch name and resolved docker build errors

- coral/permissions/casbin.py
- coral/settings.py
The recent Arches upgrades changed the signature of some permissions functions. This allows `graph_id` to be passed to `user_has_resource_model_permissions`. Also tidies some stray debug.
Go to the related resources manager and confirm that there are no 500 errors.
> Corrects permission method signature to match 7.5.0/7.5.1

- coral/permissions/casbin.py
- requirements.txt
Only warn (not error out the request) if a Django group or user that is attached to a resource instance is missing. This can happen for several reasons, and a nicer way of handling this (perhaps, like EmptyConcept...) would be good.
Additionally, this moves from caching Django Group names in Casbin by attaching the user to them, to instead making the spelt name a Casbin grouping about the UUID group name. This will be reset on rerunning `recalculate_table` but means that user-group membership can deal only with the UUIDs, and the spelt-out name will get/lose the user transitively.
> Fix admin permissions

- requirements.txt
It adds a GeoJSON datatype, that allows for JSON to be set into the geomtery field. This means the API supports GeoJSON.
> Add GeoJSON ORM datatype

- coral/media/js/views/components/plugins/open-workflow.js
- coral/plugins/open-workflow.json
- coral/settings.py
- coral/templates/views/components/plugins/open-workflow.htm
Prevents an error being thrown if a resource in the local cache is no longer available (for example, due to a reset).
This is trickier - it was originally seen after a DB reset but it should be sufficient to test by deleting the resource after doing the workflow.
@taylorn01 to confirm the fix. @hristiyanadeliyska or Jana to test on dev & UAT.
> fix(Flag for Enforcement Workflow): Save even if bad recent resources found, e.g. from before a reset [#1712]

- coral/media/js/views/components/widgets/auto-generate-id-widget.js
- coral/templates/views/components/widgets/auto-generate-id-widget.htm
On edit page params.config is not available and the language display value look up is messy and was returning a stringified object
> Fix: auto genereate id edit page rendering

- coral/plugins/open-workflow.json
Test:
Click curatorial inspection workflow from workflows page. Be redirected to open curatorial page. Start new curatorial to get one into the system. After you have that check it is the only thing shown in the select box on the open curatorial page. Also create other consultations like planning to check their prefix CON doesn't appear, only CIN should appear.
> Fix: curatorial not showing correct open list

- coral/management/commands/coral.py
- coral/plugins/evaluation-meeting-workflow.json
Test:
Run `make manage CMD="coral reload"` the command should run smoothly with a final message printing `Plugins and widgets have been reloaded.`. Test making a name or wording change in one of the workflow files is reflected into the application after running the command.
Note:
- I had accidentally forgot to update the naming of the file when renaming the workflow for `evaluation-meeting-workflow.json`. The command will only correctly match files to the slug that is defined within the JSON. 
- You will need to run the `unregister` plugin for the old name and then run `coral reload` which will then register it since it cannot find a plugin with a matching name to perform an update.
> Fix: coral reload command

- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/media/js/views/components/plugins/workflow-builder-loader.js
- coral/media/js/views/components/workflows/excavation-license-workflow/excavation-report-step.js
- coral/media/js/views/components/workflows/workflow-component-abstract.js
- coral/pkg/graphs/resource_models/License.json
- coral/templates/views/components/workflows/workflow-component-abstract.htm
Issue with saving many excavation report tiles and freeze of page if report was uploaded without validated document name field.
Changed cardinality to n 
Made a custom version of the workflow-component-abstract
Added a disableAdd button which is passed to the loaded component
Created a custom component for the nodegroup for the report
Disable and enable the add button if the mandatory field is filled
This also fixes the edit button which was not working
Reload the License model
coral reload
Navigate to the excavation report page
Try to add a report without the name, the add button should be disabled
Enter the name and the add button should be enabled
Add one report and save and continue
Return to the excavation report and the report should still be there
Add another report and save again …
> Fix(Taiga #2033 | License): Fix Excavation Report

- coral/media/js/views/components/widgets/datepicker.js
The 'Flagged Date' was populating on load but not triggering the save and continue. And not saving when additional data was passed into the step.
Removed the update to the tile data of the datepicker and let the save and continue handle the saving of the data.
Update widgets
Updated webpack
Open an enforcement - Date should be populated with today's date and the save and continue button should be visible
Hit save and the date should show in the summary page
Check the resource instance that the date has saved correctly
> Fix (Taiga #2022 | Enforcement): Pre-populated Date Not Saving

- coral/media/js/views/components/plugins/merge-workflow.js
- coral/media/js/views/components/plugins/relate-two-monuments-workflow.js
- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-ihr-workflow.json
- coral/plugins/add-monument-workflow.json
- coral/plugins/archive-catalogue-workflow.json
- coral/plugins/assign-consultation-workflow.json
- coral/plugins/curatorial-workflow.json
- coral/plugins/evaluation-meeting-workflow.json
- coral/plugins/excavation-site-visit-workflow.json
- coral/plugins/fmw-inspection-workflow.json
- coral/plugins/hb-planning-consultation-response-workflow.json
- coral/plugins/heritage-asset-designation-workflow.json
- coral/plugins/hm-planning-consultation-response-workflow.json
- coral/plugins/incident-report-workflow.json
- coral/plugins/scheduled-monument-consent-workflow.json
Most workflows have a save and continue button on the last step, this has been changed to just a save button
- coral reload
- check each workflow that the last step shows a save button and not save and continue
- check that the save button is saving the data to the resource
[Taiga](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2145)
> Fix(#2145): Change last workflow step to have save button

- coral/media/js/viewmodels/workflow-step.js
- coral/plugins/add-garden-workflow.json
- coral/settings.py
Update the Descriptions tile to a many tile to allow for multiple descriptions to be saved
Update the title that is shown on the many input box to match the node group
- Run coral reload
- Update webpack
- Start a new add garden
- Navigate to Heritage Asset Details
- Add a new type and description
- Hit Add
- Add a second
- Save and continue
- Check the resource to see if the descriptions saved
> Fix(#21115): Add Gardens Description to Many

- coral/media/js/views/components/workflows/assign-consultation-workflow/pc-summary.js
- coral/views/open_workflow.py
Add additional data to the summary pages on HM and HB response workflows
**Test**
- Fill out all fields of a planning consultation. Assign it to both teams on the action step
- Goto HM 
- Check Summary has all the fields explained in the ticket
- After add new assigned to and re-assigned to
- Double check they now appear on the summary page
- Next do the same onto the HB workflow
> Feat(#2095): add target date, address details and team assignments to summary

- coral/functions/hb_number_function.py
- coral/media/js/views/components/plugins/workflow-builder-loader.js
- coral/media/js/views/components/workflows/generate-hb-number.js
- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/pkg/reference_data/collections/collections.xml
- coral/pkg/reference_data/concepts/Wards_and_Districts.xml
- coral/plugins/add-building-workflow.json
- coral/templates/views/components/workflows/generate-hb-number.htm
- coral/urls.py
- coral/utils/hb_number.py
- coral/views/hb_number.py
- coral/views/smr_number.py
Implements the functionality needed to create a new HB number according to the HED format
**Test**
- Register new Wards and Districts concept
- Update collections so the new concept is loaded
- Reload the Monument model
- Reload the Revision model
- Reload webpack
- Reload plugins
- Go to the Create Building workflow, complete the first step and navigate to finish
- New Generate HB component should be at the bottom
- Check dropdown is rendering correctly
- Select an option and hit generate
- The new HB Number should appear in the disabled input
- Click save at the bottom of the workflow
- Check the resource model HA References the HB number should be present
- Check the resource model Wards and Districts the HB Number should be present
- Because this was the first …
> Feat: hb number generation

- coral/functions/ihr_validation_function.py
- coral/pkg/graphs/resource_models/Monument.json
This adds validation to the IHR input field.
It will check that the string has the format 00000:000:00 and if not it will display an error message
It will also check for any existing entries in the database and throw an error if true
- Register the IHR Validation Function
- Reload the monument model
- Start an add IHR workflow
- Save and Continue to the Asset Details page
- Enter a random string eg. 'test'
- Should receive a warning error that the incorrect format is being used for the IHR
- Enter the correct format eg. 12345:123:12
- Should save successfully and show in the model resource
- After saving, start a new add ihr
- Enter the same number you previously entered
- Should throw an error that the IHR number has already been used
> Feat (#2144): Add IHR Number Validation

- coral/media/css/dashboard.css
- coral/media/css/project.css
- coral/templates/views/components/plugins/dashboard.htm
- coral/views/dashboard.py
Added in a message that checks how far from the deadline the task is.
It will display 'Overdue' when the deadline has passed
Will display a countdown from 3 days when the deadline is getting closer
- make webpack
- create a new user and add them to the planning admin group
- you will need to make them a super user in the admin panel for testing
- log in as admin in incognito window in order to change the consultation dates
- as admin create a new consultation and set the target date as today
- set the status to open
- log in as the planning admin user
- navigate to the dashboard
- the consultation should be visible
- It should say Due Today in the top right corner
- As admin change the date so that it is overdue and the message should change to overdue
- Change it to …
> Feat (#2123 & # #2124) Add deadline warning message Planning Dashboard

- coral/plugins/add-ihr-workflow.json
Moved the IHR number field from the Add IHR workflow Asset Details page to the Finish page. This is to prevent the Heritage Asset Name and IHR Number being able to save at the same time.
**Tests**
- Start Add IHR
- Save a Site Name value
- Check HA/00 Site Name appears in search
- Go add an IHR Number
- Check IHR Number Site Name appears in search
- Reverse the process and do IHR first then Site Name
- Should be IHR Number None for Site name
- Then IHR Number Site Name
> Fix(#2176): move ihr number field to last page to prevent name and ihr race condtion

- coral/utils/garden_number.py
Changed the garden number from ANT:001 to AN-001
- New Add Garden workflow
- Add a county
- Navigate to last step
- Generate Garden number
- Should see number similar to pattern on this ticket https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/1820
> fix(#1820): Garden Number - change county abbreviations

- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-ihr-workflow.json
- coral/plugins/add-monument-workflow.json
[Taiga #2114](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2114?milestone=400251)
Has not been confirmed if this is how hed want it done.
PR had asked us to change the "Citation" field on the Heritage Asset Details step of the Add-Monument-Workflow to be a resource select for Bibliographic Sources.
While doing this I saw we were just using the comment node of the Citations nodegroup
It seemed more sensible to include some of the other parts of this in a many select. This is how H.E configured it when they did the same.
Testing:
stop your containers
`make webpack`
`make manage CMD="coral reload"`
complete test sheet in description of [Taiga #2114](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2114?milestone=400251)
> Fix (Taiga #2114 | add-monument-workflow | add-garden-workflow | add-building-workflow | add-IHR-workflow): citation is bibliographic source

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
[Taiga #1966](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/1966)
removes the text node for b file number and replaces it with a resource-instance select. It does need to change the node id due to lingering rows in the db.
Notes:
While not 100% relevant to this PR, please ensure you have ihr_validation_function.py; hb_number_function.py; smr_number_function.py; and garden_number_function.py registered
**Test**
Remove Heritage Asset and Heritage Asset Revision models
`make manage CMD='packages -o import_graphs -s coral/pkg/graphs/resource_models/Monument\ Revision.json'`
`make manage CMD='packages -o import_graphs -s coral/pkg/graphs/resource_models/Monument.json'`
Go to Heritage Asset workflows and Heritage Asset Detail Steps. Ensure B File field is a resource select …
> Fix(#1966 | Heritage Asset | Heritage Asset Revision): b file is resource select

- coral/media/js/views/components/widgets/datepicker.js
- coral/media/js/views/components/workflows/workflow-component-abstract.js
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2179
Adding a date in multi tile will now save the date provided. Adding a another will have the provided value and not show invalid date.
Multi tiles can be removed and edited so they reflect after saving the step and returning. This was previously only implemented in the default-card-util but the fix is available to default-card now.
**Tests**
- Enter License Communications step
- Click add with the default date provided
- The same date should be visible in the side bar
- Change the date
- Clcik add again
- Now that date should be visible
- Don't change the date and click add again
- The same date as the last should be visible on the sidebar
- Hit save
- Return to see the same dates you saved
- Add one more …
> Fix(#2179): date picker and save multi tiles

- coral/pkg/graphs/resource_models/Consultation.json
Removes duplicated item from the dropdown
**Test**
Check "O - Outline" only appears once
> Fix(#2072): remove duplicated outline dropdown option

- coral/functions/ihr_validation_function.py
Prevents the resource that owns the unique IHR id from being including in the uniqueness check
**Test**
- Save an IHR number
- Save again and it shouldn't produce an error saying it already exists
> Fix(#2184): exclude owning resource from ihr validation

- coral/views/dashboard.py
The tasks were not sorting correctly when sorted by date and running across multiple pages. This sorts the tasks when they are pulled from the cache and fixes the issue across the pagination
See here for test [Taiga #2197](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2197)
> Fix (#2197): task date sorting issue

- coral/functions/generate_ha_name_function.py
- coral/media/js/views/components/workflows/generate-garden-number.js
- coral/settings.py
- coral/utils/garden_number.py
- coral/views/garden_number.py
Noticed that if the county changes after saving the garden number does not update.
There was also an issue when you have saved the garden number and then regenerate the number, the widget errors
- Start 'Add Garden'
- Select a county from the location step
- Go to the finish step and generate a number
- Check the increment is either the first number for that county or the next consecutive (there was an issue with it incrementing the last garden number rather than a specific county)
- Click save
- Check in the search that the garden number is as it was generated and showing
- Go back to the workflow and click generate
- The widget should be fine and the garden number should not change
- Go to the location step and change the county
- Go back to the finish step and click generate garden …
> Fix/2254 Allow Garden Number to update if the county changes

- coral/media/js/views/components/workflows/assign-consultation-workflow/pc-summary.js
- coral/settings.py
In the HM response, the application summary was showing the townland node in the county descriptor.
- make webpack
- coral reload
- Start a planning consultation. Assign to HM and set a county in the location step
- Open the same consultation in HM response and navigate to the application summary
- Should see the county label showing the chosen county
> Fix(#2213): HM Response - change county node id in the application summary description

- coral/media/js/views/components/workflows/summary-step.js
- coral/settings.py
The summary component rendered the raw display value for dates which showed the American format.
**Tests**
- Open Planning Consultation
- Fill in a couple of dates target date on the last page is good
- Assign to one of the teams or both
- Navigate to the response workflows
- Confirm the summary page is rendering the UK format for dates
> Fix(#2262): if display value has a date pattern it will be changed to the uk format

- coral/media/js/views/components/workflows/fmw-workflow/get-selected-monument-details.js
- coral/plugins/fmw-inspection-workflow.json
- coral/settings.py
- coral/templates/views/components/workflows/fmw-workflow/get-selected-monument-details.htm
[Taiga #2280](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2280)
Changes in this PR:
- Added a Search String to the resource select to only include Monuments with an SMR
- Added `allowInstanceCreation: false` to the resource select to restrict users (this allowed new HA's without an SMR to be selected)
- Change label from "SMR Number" to "SMR Number(s)" to highlight that multiple can be selected
- Change the "SMR" field of the additional information card to show SMR number rather than HA number
- Change the "Townland" field of the additional information card  to use the Townland node in the Addresses nodegroup rather than the administritive localities node group
- Adds a "B File(s)" field the the additional information card
- Removes the consultation's "B File" Node from …
> Fix(Taiga #2280): fmw inspection display b file

- coral/media/js/views/components/plugins/open-excavation-site-visit-workflow.js
- coral/media/js/views/components/workflows/excavation-site-visit-workflow/get-selected-license-details.js
- coral/plugins/excavation-site-visit-workflow.json
- coral/plugins/init-workflow.json
- coral/plugins/open-excavation-site-visit-workflow.json
- coral/plugins/open-workflow.json
- coral/settings.py
- coral/templates/views/components/plugins/open-excavation-site-visit-workflow.htm
- coral/templates/views/components/workflows/excavation-site-visit-workflow/get-selected-license-details.htm
[Taiga #2158](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2158)
- adds a new plugin open-excavation-site-visit-workflow
- removes logic for the excavation site visit workflow from open-workflow.json as it's not using the standard open-workflow
- open-excavation-site-visit-workflow creates a new resource and adds the "Site" activity as a related activity - this fixes [Taiga #2251](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2251)
- adds a hidden resource select to the initial step which we use to continue using the newly created resource
- removes the resource select for the licence needed to create additional displayed information
- adjusts the licensee label to licensee(s)
- re-creates the selected-licence widget to use the new open logic - this also …
> Fix(#2158 | #2151 | #2247 | open-excavation-site-visit-workflow): excavation site visit licence is read only

- coral/media/js/views/components/widgets/datepicker.js
- coral/settings.py
Error was found on the merge workflow but it applies to all dates that are defaulted with today's date. A good double check of the other places dates have been used is needed.
**Tests**
- Open merge workflow
- Get to the Approval step
- You should see a date populated with today's date
- The save button should be visible
- Click save take the MRT reference and search for it
- IN time-spans on the matching model you should see today's date that you saved
- Start a new merge workflow and provide a different date
- Should be the same outcome on the model
- Try the date widgets on the Licensing workflow Application Details step
- Try the multi tile date widgets on the Licensing workflow Communcations step
> Fix(#2201): mark form dirty after setting today's date

- coral/settings.py
- coral/templates/views/components/workflows/excavation-site-visit-workflow/get-selected-license-details.htm
Does what it says.
**Tests**
- Check that the component will render as licensees and not nominated excavation directors (refer to changes)
> Fix(#2158): revert back to licensees

- coral/settings.py
- coral/wkrm.toml
After digging into the ORM, there is no sensible way to do this without properly implementing support for a card-defined structure. Basically, `nismr_numbering_type` is not a semantic node, it is a concept, and the structure of the ORM cannot simultaneously handle it being both without some breaking hacking. For now, this works OK to remap the generated SMR to a top-level string field, `generatedSmr` or `generated_smr` (depending on GraphQL or Python).
> Fix(API): add the generated SMR as an alias

- coral/settings.py
- coral/tasks.py
Adds a remote call to launch a database reset.
***How do we prevent accident resets?***: this only functions if it finds an upgrade window file, which must be added to the Flux repo as a mountable configmap. It lists windows, so we can extend it and so approve database resets by PR, with each window requiring a tuple: start time, end time and a window-specific "lock" password that must be encrypted by the same Arches instance. The reset command takes only one argument, a separately encrypted password (command for encrypting this is a nice-to-have) which is checked against any matching window.
If the window-password matches a (the) current upgrade window, then an upgrade will be triggered on the worker.
Walk through the documented steps on dev, and ensure a full reset is completed without …
> On-demand resets

- coral/settings.py
- coral/templates/views/components/cards/dashboard-card.htm
- coral/views/dashboard.py
This PR changes the 'Issue Date' on the task to 'CM Reference'
It then removes 'Issue Date' from the sort options and instead adds a 'Created At' which is dependent upon the time the resource was created.
- Reload the containers 
- Run through the tests here [#2474](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2474)
> Fix #2474 | #2466 - Excavation Dashboard - Change Issue Date to CM Reference - Created At Sort Order

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/settings.py
- coral/templates/views/components/plugins/open-incident-report-workflow.htm
Change the Field Worker and Owner labels to plurals
Change the placeholder text for the initial monument selection to say Heritage Asset
Updated the following from a resource instance to a resource instance list:
- Issue Identified by
- Area Archaeologist
- CWT Area Supervisor
- Occupier
Also updated the labels to add plurals
- Remove the monument model
- Reload the monument
- Run webpack
- Follow tests here [#2557](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2557)
> Fix #2557 #2558 | Monument | Monument Revision - rename input field labels

- coral/media/js/views/components/workflows/related-document-upload.js
- coral/plugins/incident-report-workflow.json
- coral/settings.py
The incident report name was not reflected in the uploaded documents making them difficult to find. 
Added a config to allow a string node to be added to the end of the uploaded documents resource name. This is then used to add the incident report reference number.
- Webpack rebuild
- Coral Reload
- Follow tests here [#2565](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2565)
> Feat(#2565) - Upload Name

- coral/media/js/viewmodels/card-component.js
- coral/media/js/viewmodels/map-editor.js
- coral/media/js/views/components/cards/default.js
- coral/plugins/incident-report-workflow.json
- coral/settings.py
- coral/templates/views/components/map-widget-editor.htm
Disables the map edit by removing the button from the map menu. This can be set in the config of the workflow
- Webpack rebuild
- Coral reload
- Follow tests here [#2560](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2560)
> Feat(#2560):  Disable map edit

- coral/media/js/views/components/reports/organization.js
- coral/media/js/views/components/reports/scenes/all.js
- coral/settings.py
- coral/templates/views/components/reports/organization.htm
- coral/templates/views/components/reports/scenes/all.htm
Updated the info button for an organisation when used in a resource instance list.
Used the all report template created for the full report and added in functionality to control the node groups that are listed as well as disabling the related resources.
- Webpack rebuild
-  Run the update_reports.sh from the coral-arches folder(in the taiga link below)
- Follow tests here [#2563](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2563)
> Feat #2563 Organisation Contact Info Report

- coral/media/js/viewmodels/card-component.js
- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/media/js/views/components/workflows/excavation-licence-workflow/excavation-report-step.js
- coral/views/dashboard.py
This changes how the report status data is pulled for the excavation dashboard. We now get the classification date, sort the tiles and get the most recent.
The classification date has then been made mandatory, this is done through the nodeOptions which have been updated to allow for configurations of the node.
The disable add has also been updated on the custom component to only show add once both classification date and document reference have been entered
- coral reload
- rebuild webpack
- follow tests - [#2608](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2608)
> Fix/#2608 Excavation Report Status

- coral/functions/notify_planning.py
- coral/media/js/views/components/plugins/dashboard.js
- coral/templates/views/components/cards/dashboard-card.htm
- coral/templates/views/components/notification.htm
- coral/views/dashboard.py
Fixes some issues that appeared on the dashboards:
- The open link in the notification only directed to assign consultation. It will now redirect to the correct team response depending on the user
- An error sometimes occurred that filter options was used before being initialised. Initialised an empty array to stop this.
- A bug that could reset the assigned user when looping through several tiles. Now breaks when truthy is found
- No notification was sent when a response had been completed. Should notify the planning admin of a completed response of the team
- Reload the Notify Planning function
- Either reload the consultation or add the function back onto the model
- rebuild webpack
- Create or use a user for both the HM and HB groups
- Create a planning admin and …
> Fix #2623: Dashboard fix

- coral/media/js/views/components/plugins/view-enforcements.js
- coral/settings.py
- coral/templates/views/components/plugins/view-enforcements.htm
The enforcements were erroring on some resources as description data was not available and the error was not being handled. 
- Create multiple enforcements, some with name and descriptions, some with no description and some saved with no data
- Navigate to the enforcements dashboard
- Should see all the enforcements
- Should see status were applicable, description and a title name
- No errors should be present in the console
> fix(#2484): enforcements not showing correctly

- coral/media/js/views/components/reports/scenes/all.js
ReportViewModel does not have this set by default and JSON requests don't work as they look for the resource iD.
> Ensure all has resourceid set

- coral/plugins/hb-planning-consultation-response-workflow.json
- coral/settings.py
HB Response had the planning consultation assign node still showing. This removes it.
- coral reload
- rebuild webpack
- create a planning consultation assigned to hb
- assign a user
- open the hb response
- check on assign step that only one assign to node is visible and that it is disabled
- should have the user previously selected visible
> hotfix: remove extra assign node from hb response

- coral/settings.py
Pulls in `str` comparison fix in arches fork: [https://github.com/flaxandteal/arches/blob/master/arches/app/models/resource.py](https://github.com/flaxandteal/arches/blame/0dbebb23731ad1aff3d4796e6be331ddc17548f4/arches/app/models/resource.py#L266)
> 2650: Fix full reports not showing

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/settings.py
The category types on the monuments had reverted to an old domain list. This has been updated to match what is expected.
- Reload Monument and Monument Revision
- Check on the model - Category Type, domain list should include:
- Lacustrine
- Carved Stone
- Field Monuments
- Standing Buildings
- Riverine
- Marine
- Go to the add monument workflow
- In asset details check that these are showing in the category type drop down
> fix(Monument | Monument Revision): update category type domain list

- coral/plugins/assign-consultation-workflow.json
- coral/settings.py
Remove 'Date Consulted' from the 'Assign Consultation' 'Assignment Details' step.
- coral reload
- open planning consultation
- navigate to the assignment details page
- make sure date consulted is not visible
> fix(#2674): remove date consulted from assign consultation

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/plugins/hb-planning-consultation-response-workflow.json
- coral/plugins/heritage-asset-designation-workflow.json
- coral/plugins/hm-planning-consultation-response-workflow.json
- coral/settings.py
This PR adds 
Council Consulted Date
Council Response Date
Council Response
Priority Rating
to heritage asset and heritage asset revision.
It trims unused Node Options and adds the new nodeOptions for the new dates.
It renames the Action Step to Summary.
To test you'll need to delete and re-import heritage asset and asset designation,
coral reload
Make a heritage asset
Go to the incident report workflow and check that there is a priority rating in the proposal step.
Ensure the domain options 1-5 are available
Go to the heritage asset designation workflow
Ensure Council Consulted Date,  Council Response Date, Council Response nodes are present in the Approval step
Ensure all dates are still limited to today as the max date
Go to the response workflows, check the action step has been …
> Feat #2660 #2666 #2667 #2668 

- coral/functions/transfer_licence_function.py
- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-ihr-workflow.json
- coral/plugins/add-monument-workflow.json
- coral/settings.py
This PR makes description and description types mandatory for heritage asset many selects
needs a coral reload
Test:
```table
Workflow           | Step          | Field            | Mandatory Fields                  | Pass/Fail
Add IHR            | Descriptions  | Description Type | “Description Type”, “Description” |  
Add Building       | Description   | Description Type | “Description Type”, “Description” |  
Add Monument       | Description   | Description Type | “Description Type”, “Description” |  
Add Garden         | Description   | Description Type | “Description Type”, “Description” |  
```
I've also accidentally added the fix for #2369 here as well.
To test it you will need a coral reload then create a licence.
Then use the amendments step to transfer the nominated excavation …
> fix(#2237): heritage asset descriptions are mandatory

- requirements.txt
Bumps Arches ORM to 0.1.3 to avoid an exception when descriptors not yet set.
> Bump Arches ORM to 0.1.3

- coral/settings.py
- coral/templates/views/components/plugins/dashboard.htm
- coral/views/dashboard.py
The Excavation team wanted the newest task showing at the start of the list. Need to change the sort order to be desc by default. This needed to change the list order for the drop down so that desc was first and needed to change how the tasks were sorted on the backend when first fetched. Because of the change on the front, the planning team also now has default desc to show the newest task first.
- Follow [tests](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2743)
> #2743 Fix (dashboard): set default sort order to desc

- coral/media/js/views/components/workflows/licensing-workflow/fetch-updated-dates.js
- coral/settings.py
The valid until date was being created exactly 6 months after the issue date, 6/12/24 - 6/6/25. This needs to be one day before this - 5/6/24
- Coral Reload
- Follow tests here [#2741](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2741)
> Fix #2764 Minus 1 day from the valid until date

- coral/media/js/views/components/plugins/view-enforcements.js
- coral/settings.py
- coral/templates/views/components/plugins/view-enforcements.htm
Increased the amount of tasks showing per page on the enforcement dashboard.
This was closely coupled with the advance search pagination which only allowed 5 items per page.
This has been rebuilt with the pagination in the js to allow for control over how many items are shown.
- Navigate to the Enforcement page
- Should see 12 tasks per page
- Navigation should direct to a new page
> #2742 Fix: Increase tasks per page enforcement dashboard

- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/pkg/graphs/resource_models/Licence.json
- coral/settings.py
- coral/views/file_template.py
Fix the excavation letters to use the Generic Template to pull the node values and generate the letters.
This also adds 2 new letter templates to the drop down list for a total of 6 letters:
- Licence Covering Letter
- Final Report Letter
- Extra Name on Letter
- Extension of licence letter
- Overdue excavations report letter
- Transfer of licence letter
Changed the model to use a concept instead of a domain value list
- Reload licence model
- Import the concept list and collections from [here](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2705?milestone=418255)
- restart containers
- coral reload
- webpack rebuild
- follow tests here [#2705](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2705?milestone=418255)
> Fix/#2705 Excavation Letter Templates

- coral/permissions/casbin.py
- coral/settings.py
- coral/utils/casbin.py
Ensure plugin IDs consistent, even if deletion is required. On update, this will check that every Django Plugin has a matching Arches Plugin whose UUID is consistently derived from the slug (if possible). If it finds any where it is not, the Arches Plugin will be deleted and replaced with a new Arches Plugin with a consistent UUID.
This should allow reuse of resources between instances/databases that reference Arches Plugins by ID (such as Groups), without needing to copy the Arches Plugin resources themselves.
Running:
docker exec -ti coral-arches_worker-1 /bin/bash -c ". ../ENV/bin/activate; celery -b \$CELERY_BROKER_URL call coral.tasks.recalculate_permissions_table"
and checking if [Add Building](http://localhost:8000/resource/61ffe499-4864-a03d-0dc9-c4075661dabc#) is present as Add …
> Ensure Arches Plugin IDs are consistent, based on the slug (if poss.)

- coral/media/js/views/components/plugins/dashboard.js
- coral/settings.py
- coral/views/dashboard.py
This adds filtering drop downs to the planning dashboard for individuals within the groups and for groups themselves.
This is based around what group the user is in.
If in the planning group the user will see:
- HM Group filter
- HB Group filter
- All HM users
- All HB Users
If in either HM or HB Group:
- No group filter
- Only users within the respective group
The person filter filters based on the assigned to node
The group filter filters based on the action type which is assigned to hm, assigned to hb or assigned to both
- Follow tests [#2770](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2770)
> Feat (#2770 | #2771) Filter by individuals and Groups

- coral/media/js/views/components/workflows/evaluation-meeting-workflow/get-designation-details.js
- coral/settings.py
This PR fixes the issue where buildings that do not have a grade continue to show "Loading..." in the evaluation step when they are intended to show "None" when it's determined that there is no Grade.
Test
Make 3 heritage assets, 2 buildings and one which is not a building
With one of the buildings, complete the designation workflow and ensure you add a grade.
| Test | Expectation |
--- | --- |
Select the Evaluation Meeting Workflow | should go to an open workflow page |
Observe the page | There should be 2 dropdowns, "Start New" and "Open Selected" should be disabled |
Observe the first dropdown | it should have the placeholder "Please Select the Building" |
click the drop down | should show ONLY the buildings |
Select a building | "Start New" should be enabled, "Open Selected" still …
> fix (#2779): force grade to update after checking tiles

- coral/settings.py
Makes email parameters settable via env.
Add the relevant parameters and set the backend to `django.core.mail.backends.smtp.EmailBackend` then attempt to reset your password. It should take you through the full flow.
@StuCM @OwenGalvia
> Make email parameters settable

- coral/templates/views/components/workflows/file-template.htm
This fixes the issue that is hiding the letter options drop down.
- The letter options was pointing at an observable and was always reading it as true instead of reading the value. Unwrapped the observable
- Also added in a placeholder param when letter options are added as this was creating an error when deleting selection.
- Added some formating to the htm to improve readablility
- Check the SMC workflow letters - Should see a 'Select an Option' place holder
- When clicking the drop down should see the following options:
-  "SMC Addendum Letter"
-  "SMC Provisional Letter"
-  "SMC Refusal Letter"
-  "SMC Final Letter"
-  "SMC Final No Conditions Letter"
-  "SMC Provisional No Conditions Letter"
-  "SMC-CL Provisional Letter"
-  "SMC-CL Final …
> hotfix: Show letter dropdown without letterOptions param

- coral/settings.py
- coral/views/dashboard.py
This adds the permissions to the planning group users and the SMM users, limiting what workflows they can see and what resources they are able to see.
This does not limit what they are able to create and delete. The permissions for this did not work with the current implementation of permissions.
- You need to work on dev to test
- Add users into each group to test, users have been set up here - [Planning Users](https://docs.google.com/spreadsheets/d/1NTklj81mw82TI6h_wefEaljrzdIhTm0CWmMTigNuRXc/edit?gid=0#gid=0) 
- Follow the tests here - [#2812](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2812?milestone=424249) [#2835](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2835?milestone=424249)
- The dashboard fix for the users will need to be tested locally.
- Add …
> Fix/#2812 #2835 Planning Group and SMM Permissions

- coral/settings.py
- coral/views/file_template.py
This is a fix for the letter generation bug that appeared for a completed Monument in the all of the workflows.
The error stemmed from the Map data being processed as a string during the mapping of the template.
- Complete a new monument - fill out all data including a map location
- Open Designation workflow and start a new process with the monument
- Reopen the REV and navigate to the letters step
- Generate any letter
- The letter should generate without any error in the console
> fix: error check list values

- coral/pkg/graphs/resource_models/Heritage Asset Revision.json
- coral/pkg/graphs/resource_models/Heritage Asset.json
- coral/settings.py
The 2 models shared an edge node id for one of the nodes. This was causing export issues for which ever model was loaded first.
> Fix (Heritage Asset | Heritage Asset Revision): #2917- Correct duplicated edge node ids

- coral/media/js/viewmodels/workflow.js
- coral/settings.py
- coral/templates/views/components/plugins/workflow.htm
[#2930](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2930)
This fixes the issue with node options from the workflow not applying when going back or using the tabs to navigate through the steps. It updates the step each time it is navigated to as to pull the config from the workflow json.
- Navigate to a workflow using the node options - (example - Planning Consultation - Assessment Tab - DfI Calendar node)
- Check that the node options have applied
- Navigate to another step
- Navigate back use the previous button at the bottom
- Check if the node options are still applied
- repeat the process several times - ensure node options are always applied
- Repeat the process again but use the step tabs for the navigation
- Check for several …
> fix: apply nodeOptions on back and tab select

- coral/pkg/graphs/resource_models/Heritage Asset Revision.json
- coral/pkg/graphs/resource_models/Heritage Asset.json
- coral/settings.py
This updates the Heritage Asset and Heritage Asset Revision 'Damage Type' node to use the Historic England Threats
The concepts have been updated and will show additional drop downs
Import the concept and the collection to your local branch, can be found here:
[#2819](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2819)
Reload the models for HA and HA Revision
Open the Issue Report and navigate to the Record of the Issue
Open the Damage Type and you should see the Historic England Threat Types
Search for:
Field Improvement – Should be a child to Agricultural Requirements
Clearance – Should be a child to Field Improvement
Cultivation – Should be a child to Agricultural Requirements
Tree planting – Should be a child to Cultivation and Gardening
Reservoir – Should be a child to …
> Fix (Heritage Asset | Heritage Asset Revision): Update Damage Type Concept

- coral/settings.py
- coral/utils/ha_number.py
The tile data was being sorted by the creation time of the resource instance which was causing issues when re-importing the data. This will organise by the actual HA number when querying the database.
[Heritage_Asset_2025-02-19_12-05-50 copy.json](https://github.com/user-attachments/files/18867911/Heritage_Asset_2025-02-19_12-05-50.copy.json)
[HA01.json](https://github.com/user-attachments/files/18867912/HA01.json)
In `utils/ha_number.py` change the generate_id_number retry attempts to 5 just for testing
- Import the `Heritage_Asset_2025-02-19_12-05-50 copy.json` - this imports HA/02 - HA/10
- Import `HA01.json` this imports HA/01.
- This should break the original method - if possible try this on the standard dev branch to see if the break occurs
- Reload the current branch and restart …
> Fix: filter and sort tiles by HA number

- coral/media/js/views/components/reports/heritage-asset.js
- coral/media/js/views/components/reports/scenes/enforcements.js
- coral/settings.py
- coral/templates/views/components/reports/heritage-asset.htm
- coral/templates/views/components/reports/scenes/enforcements.htm
This PR adds a very basic enforcement scene for heritage asset reports. 
It's simply the name of any enforcements that relate to the heritage asset which serve as links to the respective enforcements report.
Test:
Create a heritage asset that has one or more enforcements flagged about it.
go to the heritage asset's report page
go to pending enforcement step
enfrocements should be present and clickable
As an enforcement admin mark one of the enforcements as received.
As a non admin, go back to the enforcement scene
The received enforcement should not be present.
> feat: new enforcement scene

- coral/management/commands/migrate_safely.py
- coral/pkg/graphs/resource_models/Heritage Asset Revision.json
- coral/pkg/graphs/resource_models/Heritage Asset.json
Adds features to allow you to remove the members from the groups and rehydrate the groups with new members from the current environment.
To remove members run:
`python manage.py migrate_safely -o remove_members`
This will export a backup file with the members and an empty groups file to:
`coral/pkg/business_data/files`
To rehydrate you need to be in the environment that has your members. You will need to move the new empty group model into your environment and then run:
`python manage.py migrate_safely -o rehydrate_members -s 'empy_members_model'`
This will then add the members into the updated group, export the data to the business data, remove the old groups and import the updated groups with the members
- Import the groups
- Add links between groups in the members
- Add person …
> Feature: Update Groups

- coral/plugins/agriculture-and-forestry-consultation-workflow.json
- coral/settings.py
Updated typo in agriculture letters dropdown `Foreestry Response Letter` to `Forestry Response Letter`
- Clone branch and run `make manage CMD="coral reload"` 
- Then go to Agriculture and forestry workflow and ensure that the correct spelling is present in the letters dropdown 
@StuCM @OwenGalvia
> fix: fixed typo in agriculture letters dropdown

- coral/functions/notify_planning.py
- coral/pkg/graphs/resource_models/Consultation.json
- coral/settings.py
This updates the logic for the planning notifications.
The save type has been changed to `save` instead of `post_save`
Logic has been updated to send to admins when it is assigned
Additional notifications have been added to allow multiple groups with different workflows assigned to be updated at the same time (slug was originally changing depending on the last group updated)
The model also did not have all the triggering functions set on it.
- Reload the consultation model
- Follow the tests here [#2725](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2725?milestone=431103)
> Fix (Consultation): #2725 Planning Notifications 

- coral/pkg/graphs/branches/Council.json
- coral/pkg/graphs/resource_models/Activity.json
- coral/pkg/graphs/resource_models/Consultation.json
- coral/pkg/graphs/resource_models/Heritage Asset Revision.json
- coral/pkg/graphs/resource_models/Heritage Asset.json
- coral/settings.py
Models updated: Consultation, Activity, Heritage Asset, Heritage Asset Revision
Branches updated: Council
This updates the council lists for the above models. It uses the new NI council list and orders them correctly
Reload the models listed above, reload the council branch first
Follow tests here - [#2884](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2884?milestone=433804)
> Fix (Multiple Models): update the council domain list

- coral/management/commands/apply_sets.py
- coral/settings.py
- coral/utils/casbin.py
- Checks whether a sets member is null, as arches#coral-7.6 now has that possibility
- Adds a flag to force synchronous execution of update-by-query to see errors.
1 - Try creating a logset that matches everything
2 - Create a new resource that will be matched
3 - The resource is correctly matched and the visibility updates with the new resource
---
Run `apply_sets` manually with `python manage.py apply_sets --synchronous` on an instance with logsets and many resources.
See Elasticsearch timeout as the run takes too long.
You can try introducing an issue to the Painless script, if running locally, and this will appear only when the `-S` flag is used.
@StuCM or @OwenGalvia
> #2992: cover null sets in ES and --synchronous for apply_by_sets

- coral/urls.py
So far I'm just trying to reuse the temp_files endpoint but with api/ prepended to perhaps allow permission to credential grant types
> feat: reuse temp file endpoint as an api one

- coral/templates/views/components/reports/scenes/enforcements.htm
This removes the a link from the Enforcement ID when displayed on the report page of a Heritage Asset
**Related Task:** [3062](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/3062)
---
Updates the enforcements.htm to use a span instead of a 
---
---
---
---
---
---
```
make run
make webpack
```
[List any tests that need to be run to verify the changes.]
--- …
> Fix: 3062 Enforcement Report Link Removal

- coral/settings.py
- coral/views/dashboards/dashboard_utils.py
- coral/views/dashboards/excavation_strategy.py
- coral/views/dashboards/planning_strategy.py
The Planning managers and Users dashboards were failing to load and looked as though a timeout was happening. This was due to the deepcopy of the queries being made. This was too intensive and was causing failures. This adds a method to rebuild the query to use for collecting counts
---
- Update the planning strategy to remove deep copy
- Update excavation strategy to remove deep copy
- Change filter comparison to lowercase all in excavation
---
---
---
[Describe any new concepts or terms introduced, and explain how they integrate with …
> Hotfix Planning, Excavation Dashboard Loading Error

- coral/media/js/viewmodels/workflow.js
- coral/plugins/evaluation-meeting-workflow.json
- coral/plugins/issue-report-workflow.json
When opening an issue report and evaluation meeting all tabs were enabled. It was due to the fact that issue report and evaluation meeting are nodegroups in the HA model. If the HA model had the map tile saved, it would reference this in the issue report and assume it had been completed. Subsequently if location details was present (it is a required tile) then evaluation meeting had the same issue. This will add an additional arg that can be put in the workflow config 'ignoreComplete' which will allow the workflow to skip the step from setting the workflow as completed passed the required nodes
**Related Task:** 
[3079](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/3079)
[3085](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/3085)
---
- Add a check in the …
> Fix: 3079 3085 Evaluation Meeting and Issue Report tabs

- coral/media/js/views/components/workflows/default-card-util.js
- coral/settings.py
- coral/templates/views/components/widgets/resource-instance-select.htm
The info button for the resource instance select was only showing one card. Updated to show the full report and hide the empty nodes
**Related Task:** [2261](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2261)
---
- Change resource instance select summary to false
- Updated system settings to hide empty nodes in reports
---
---
---
---
---
- All summary reports for instance select should be changed
---
---
---
--- …
> Fix: 2261 Report Summary Resource Instance Select - Licence

- coral/media/css/project.css
- coral/media/css/signup.css
- coral/static/js/signup.js
- coral/templates/signup.htm
On signup there were no indicators to highlight what was incorrect with your password. This adds green and red indicators to each category to highlight if your password in incorrect
**Related Task:** [2065](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2065)
---
- Updated the signup.htm to use a js script
- Created a static js script to validate the password before submitting
- Added CSS classes for validation
---
---
---
---
---
---
---
- (Add details here if this …
> Feat: 2065 Add colour indicators when the password criteria is met on signup

- coral/media/js/views/components/workflows/assign-consultation-workflow/pc-summary.js
In the planning consultation response summary, date consulted node was present when not needed and townland and the building name were missing from the address
**Related Task:** [2432](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2432)
---
- Removed date consulted from pc summary
- added building name and townland to the address details
---
---
---
---
---
---
---
---
- (Add details here if this change type is …
> Fix: 2432 Consultation Response Summary Nodes

- coral/management/commands/migrate_safely.py
When a resource instance was converting to a list, it was adding an extra [ ] to the value. A resource instance is already a list so this threw an error
---
- In migrate tool allow many, add a check if the node value is already a list
---
---
---
---
---
---
---
---
---
```
```
- [Include steps to …
> fix: Migration Tool Many Select Conversion

- coral/media/css/report_templates.css
- coral/pkg/graphs/resource_models/Heritage Asset Revision.json
- coral/pkg/graphs/resource_models/Heritage Asset.json
The scheduling criteria was not showing on the report. Analysing the graphs, there were errors with the nodegroup set up. Also I fixed the annoying scroll in the report
**Related Task:** [3046](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/3046)
---
- Fix the HA model issues in the JSON
- Fix the HA Revision issues in the JSON
- Add max-height css property for the reports
---
- Heritage Asset
- Heritage Asset Revision
---
---
---
---
---
---
---
- (Add details here …
> Fix: 3046 scheduling criteria not showing

- coral/pkg/graphs/resource_models/Organization.json
Organization county datatype was still set as a string
**Related Task:** [2607](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2607)
---
- Change county type in Organization model to a concept
---
- Organization
---
---
---
---
---
---
---
---
```
```
- Create a new organization
- County should be a drop down of counties
---
> fix(Organization): change county data type to a concept

- coral/media/js/views/components/workflows/licensing-workflow/fetch-generated-licence-number.js
fixed typo in license workflow notification banner
---
- Updated a typo in the Licence, open workflow description
---
---
---
---
- Licence Workflow
---
---
---
---
---
```
make webpack
```
- Go to license workflow and generate a license, the banner should have no typos
---
> fix: fixed typo in license workflow notification banner

- coral/media/js/views/components/workflows/assign-consultation-workflow/show-hierarchy-change.js
- coral/pkg/graphs/resource_models/Consultation.json
The application data was checking if the selection was in the STATUTORY_VALUES on load and setting a default selection text if not. This changes to check for a value or default text and then perform the check for hierarchy type.
The Application type was also not showing in the report section of the instance
**Related Task:** [2783](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2783)
[2943](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2943)
---
- update check against application type in the show-hierarchy-change
- make the application type card visible in the resource instance
---
- Consultation - Made Application Type card visible
---
---
---
- (Add …
> fix: check application type data on load to set hierarchy type

- coral/functions/notify_enforcement.py
- coral/media/js/views/components/workflows/enforcement-workflow/enforcement-summary-step.js
The notify enforcement did not have the check to escape the function for imports and CM ref was not showing on the Enforcement summary page
---
- add escape_function context to notify_enforcement
---
---
---
---
---
---
---
---
---
```
```
- Create an enforcement
- Head to the dashboard
- Open the respond to enforcement by clicking open
- Add …
> fix: add escape function to notify enforcement

- coral/media/js/views/components/widgets/check-open-applications.js
Last Nominated Excavation Director many select not clearing after all were deleted, this PR will fix that issue. The license message pop ups will now clear 
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2338
---
- remove info message when check application is null
---
---
---
---
---
---
---
---
- add null check to the check open application
---
```
make run
make webpack
```
- …
> fix: fixed director many select not clearing

- coral/settings.py
This PR should fix the incorrect time zone and times being displayed in the notification panel
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2503
---
- [List the changes you're proposing]
- [Be specific and concise]
---
---
---
---
---
---
---
---
---
```
make run
```
- Trigger a notification and make sure the time displayed …
> fix: added time zone details in coral settings.py

- coral/permissions/casbin.py
- coral/pkg/business_data/Logical Sets.json
The PDF files were not being listed in the PDF merger step for the planning resource when logged in as a user. This was related to the permissions not being able to access the Related Resources of a resource instance.
**Related Task:** [2818](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2818)
---
- Updated casbin to check against the user permissions as well as the Django Group permissions
- Added additional logical sets for the digital objects
- Updated the planning groups with the new logical sets (saved in the S3 bucket)
---
---
---
---
---
- (Add details here if this …
> Fix: 2818 PDF Merge Files not showing for Users

- requirements.txt
An update to the Django Debug Toolbar was causing a crash in the build. This pins the toolbar version to 5.2.0 which was the last working instance
> fix: pin django toolbar to version 5.2.0
