- coral/coral/media/js/views/components/plugins/licensing-workflow.js
- coral/coral/media/js/views/components/workflows/licensing-workflow/initial-step.js
Requests that can be send concurrently have been.
Local testing:
Without change time: 12s70
With change time: 11s60
Reason for change:
- Develop takes 1m18s23 to complete the initial step which is a full minute longer than local
- It takes 30 seconds alone just to finish the request for the tile. I have no control here this is required
- The next 45 seconds are for the other requests which should be slightly reduced to maybe 20-30 ideally. If it drops lower even better
A message has been added to let the user know to wait patiently.
> Slight improvement to the speed of the initial step, further details below

- coral/coral/media/js/views/components/plugins/licensing-workflow.js
- coral/coral/pkg/graphs/resource_models/License.json
Contacts now supports:
- Companies (resource-list)
- Applicant (resource-instance)
- Company Directors (resource-list)
- Licensees (resource-list)
New Dates group added:
- Proposed Start
- Proposed End
- Actual Start
- Actual End
- Received 
- Acknowledged
Proposal has been updated to Application Details:
- Application Details Note
Status and duration dates is now Application Status:
- Status
> Updated application details fields to match mock up

- coral/coral/pkg/graphs/resource_models/License.json
- coral/coral/settings.py
Add license valid to and from dates needs merged first
> Added decision approved by field

- coral/coral/media/js/views/components/widgets/cover-letter-widget.js
- coral/coral/media/js/views/components/workflows/licensing-workflow/license-final-step.js
- coral/coral/media/js/views/components/workflows/summary-step.js
- coral/coral/settings.py
- coral/coral/templates/views/components/widgets/cover-letter-widget.htm
- coral/coral/templates/views/components/workflows/licensing-workflow/license-final-step.htm
- coral/coral/templates/views/components/workflows/render-nodes.htm
Decision approved by needs merged first
> Add cover letter to summary step

- .github/workflows/semantic-versioning.yml
- If the branch name contains feature and the version was 0.0.0 the result will be 0.1.0
- If the branch name contains bug and the version was 0.0.1 the result will be 0.0.1
- If the branch name contains release and the version was 0.1.1 the result will be 1.0.0
> CI job for automatically increasing the version

- coral/coral/pkg/reference_data/collections/collections.xml
- coral/coral/pkg/reference_data/concepts/Planning_Categories.xml
Should be pretty straight forward, changes are only for the collections in pkg
> added planning categories concept with the drop down options

- requirements.txt
Pins the ORM, so avoid accidental rolling forward/back. In doing so, it pulls in a fix for @kanika-miglani that prevents errors depending on the order of tile saving.
Self-review for trivial bug, pre-release: @philtweir
> Transaction wrapped save in orm (pins ORM)

- requirements.txt
Extends the API with experimental concept and resource model endpoints, for superuser only.
Test the concept migration against it.
@philtweir and @kanika-miglani (but will require deployment to dev)
> Additional API endpoints

- coral/settings.py
- coral/views/dashboard.py
A node on the consultation did not exist and would cause inifinite loading on the dashboard.
Changed the path to find the node through the ORM.
Added a method to check the node and throw a console error and allow the other nodes to load.
To test this a user needs to be part of the planning admin group. 
Create a planning consultation and set the action > action status to 'HB Done' - This will create a task for the planning admin
Open the dashboard and the task should show with no errors.
> fix: correct date node and add check if node exists

- coral/media/js/views/components/widgets/datepicker.js
- coral/templates/views/components/widgets/datepicker.htm
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/1750
> Fix: date showing invalid date

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-monument-workflow.json
- coral/plugins/ihr-workflow.json
Changes to the Heritage Asset Workflows:
- Add OSNI References
- Unique Building ID
- LP Fusion ID
- BU Fusion ID
- Link Area Names, Area Type and Townland to the new data sets
The last pr hadn't correctly pushed these updates
> Add OSNI References to the HA Workflows

- coral/plugins/add-ihr-workflow.json
- coral/plugins/init-workflow.json
- coral/plugins/open-workflow.json
Run coral reload
Check add ihr is the workflow name
> fix: change IHR to add IHR

- coral/media/js/views/components/widgets/check-open-applications.js
Change message to state that the open applications includes the one just added
Add a user to the excavation licensees, Should state that 'including this one' in the message
> fix: language change on number of licenses

- coral/pkg/graphs/resource_models/Activity.json
- coral/plugins/excavation-site-visit-workflow.json
[Taiga](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/1944)
> Feat(Taiga #1944 | Activity): activity add description types

- coral/media/js/views/components/workflows/heritage-asset-designation-workflow/ha-summary.js
- coral/plugins/heritage-asset-designation-workflow.json
[Taiga #1865](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/1865)
> Fix(Taiga #1865): designation workflow irish grid ref

- coral/pkg/graphs/resource_models/Consultation.json
Change the response type dropdown editing 'Advice - Does not comply' to 'Advice - Contrary to Policy / Does not comply'
Reload Consultation model
Create a new response assigned to HM and HB
Open HB and HM repsonse
Navigate to action
Check Repsonse Type dropdown
> Fix(Consultaiton): Change response type dropdown

- coral/media/js/views/components/workflows/licensing-workflow/fetch-updated-dates.js
Valid until was being calculated from the Actual Start Date this has been changed to now work from the Issue Date.
A check has also been implemented to stop the 6 month calculation from running if the license already has a licence number.
- Open an excavation licence workflow
- Navigate to record decision step
- Fill in the issue date
- Valid until date should populate with a date 6 months in the future
- Set the stage of application to granted and save and complete the workflow (this should generate a license number)
- Open the workflow and navigate to record decision
- Edit the issue date
- The valid until date should not change
> Fix(#1838): Excavation - Create Valid Until Date 6 Months From Issue Date

- coral/media/js/views/components/plugins/licensing-workflow.js
[Taiga #2117](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2117)
> fix (Taiga #2117): amendment typo in licensing workflow

- coral/functions/smr_number_function.py
- coral/media/js/views/components/workflows/generate-smr-number.js
- coral/utils/smr_number.py
Fixes issues with SMR number component, function and view.
**Tests**
- Select Nismr
- Generate a SMR
- Save
- Spam generate
- Save
- Change the Nismr, click generate
- Spam it
Everything should work without hiccups
> Fix(#2146): smr number errors

- coral/media/js/viewmodels/workflow.js
Reverts flaxandteal/coral-arches#476
> Revert "Fix/2339 spam click duplicates"

- coral/media/js/views/components/plugins/dashboard.js
- coral/templates/views/components/plugins/dashboard.htm
- coral/views/dashboard.py
This adds a filter drop down to filter the tasks by the report status on the excavation dashboard.
- Follow the test here [#2475](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2475)
> Feat #2475 - Excavation Dashboard - Add Filter for Report Status

- coral/settings.py
- coral/templates/views/components/plugins/open-incident-report-workflow.htm
Remove the clear recent button from the start of the Incident Report
- Webpack rebuild
- Follow tests here [#2597](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2597)
> fix(#2579): Remove clear recent button

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/plugins/incident-report-workflow.json
- coral/settings.py
Updated the 'Work Carried Out by' node to be a resource instance list with Organisations
Remove the Contact Details from the incident report workflow
- Reload Monument and Monument Revision
- Coral reload
- Follow tests here [#2562](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2562)
> Fix #2562 | Monument | Monument Revision - Work Proposed Step - Incident Report

- coral/media/js/viewmodels/card-component.js
- coral/plugins/incident-report-workflow.json
- coral/settings.py
Stop future dates from showing on 'Work Finish Date' and 'Sign Off Date'
Pulled in nodeOptions config options to update maxDate from the workflow
- Reload Containers
- Coral Reload
- Follow tests here [#2564](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2564)
> Fix/#2564 - Incident report future dates

- coral/functions/update_response_assignee_function.py
Permissions branch was not allowing the action tile to be saved on a consultation. This was due to the groups not being accessible.
Added with admin() to the function that calls the Groups and Person models
- Need to test on the permissions branch
- Create a new consultation
- Move to the action step
- Fill in the details, Assign to Both, Add a person, Set Status to Open
- Should allow you to save without an error
> fix(#2622): add with admin when checking groups and person resource

- coral/media/js/views/components/workflows/assign-consultation-workflow/pc-summary.js
- coral/pkg/graphs/resource_models/Consultation.json
- coral/plugins/assign-consultation-workflow.json
- coral/settings.py
- Fixed the typo for DfI was originally listed as DIF.
- Changed all nodes on the consultation model
- Changed on the assign consultation workflow
- Changed on the summary step
-  restart containers
-  rebuild webpack
- coral reload
- follow tests here [#2675](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2675)
> fix(#2675): change DIF to DfI

- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/settings.py
Add 3 extra values to the the domain value for description type on the designation workflow Assessment step.
- Reload Monument and Monument Revision
- Tests here [#2678](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2678)
> feat(#2678 | Monument | Monument Revision) add values to assessment description type

- coral/media/js/views/components/widgets/check-open-applications.js
- coral/settings.py
- justfile
simple test is to create 7 licences with one person. Ensure no amber warning appears. When 6 licences are made and the person is selected for a 7th the banner should become red.
> fix(#2613 2614): remove warning colour

- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/media/js/views/components/workflows/file-template.js
- coral/pkg/graphs/resource_models/Monument Revision.json
- coral/pkg/graphs/resource_models/Monument.json
- coral/plugins/heritage-asset-designation-workflow.json
- coral/plugins/scheduled-monument-consent-workflow.json
- coral/settings.py
- coral/views/file_template.py
Added the file-template component into the letter tab within designation. 
Created a new concept to populate the drop down
Changed the templates to allow for data to be populated
Added 2 new templates to designation:
- Advance listing letter to owner occupier
- Advance listing letter to council
- Reload Monument Revision model
- Import the concept list and collections from [here](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2682?milestone=418255)
- restart containers
- coral reload
- webpack rebuild
- follow tests here [#2682](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2682?milestone=418255)
> Fix/#2682 Designation Letter Templates

- coral/settings.py
- requirements.txt
Pulls in a [change in ArchesORM](https://github.com/flaxandteal/arches-orm/commit/264f5d28964580e39689cd468a02a3a5b0c40456) to update the index on save in ArchesORM.
Try creating a new user. Create a Person and use the copy-link to sign up a new user. Confirm that searching for the person in Arches does not show an "Undefined" entry in the list.
> 4975 (admin board): fix undefineds on search

- coral/media/js/views/components/reports/scenes/all.js
- coral/templates/views/components/reports/heritage-asset.htm
- requirements.txt
Pulls in 2 fixes from dev:
* https://github.com/flaxandteal/coral-arches/pull/549
* https://github.com/flaxandteal/coral-arches/pull/551
> Hotfix: #4975 #2650 resolve undefined and full report issues

- coral/media/js/views/components/plugins/view-enforcements.js
- coral/settings.py
- coral/templates/views/components/plugins/view-enforcements.htm
This adds a filter selection to the enforcement dashboard. Allows the user to filter the enforcement's by status. Filter includes:
- New
- Received
- In Progress
- Closed
- All
- Follow tests here [#2768](https://tree.taiga.io/project/viktoriabon-coral-phase-2/task/2768)
> feat: #2768 add filter to enforcement dashboard

- coral/pkg/graphs/resource_models/Activity.json
- coral/settings.py
This PR makes the townland node a multi select for the activity model (and therefore the licensing workflow)
To Test,
reload the activity model
go to licensing workflow location data step
click townlands dropdown and select multiple options
> fix (#2788): change activity townland to concept list

- coral/media/js/views/components/plugins/workflow-builder-loader.js
- coral/media/js/views/components/workflows/show-nodes.js
- coral/plugins/evaluation-meeting-workflow.json
- coral/settings.py
- coral/templates/views/components/workflows/show-nodes.htm
- coral/urls.py
- coral/views/orm.py
This PR adds an orm endpoint which allows us to query for data based on a resources node alias'
It also uses this in the evaluation meeting workflow to show location data for the Heritage asset
> feat: added a show node component and use it in evaluation workflow

- coral/management/commands/export_rbac.py
- coral/pkg/business_data/Public Group.json
Shows a list of resources to which the "Public" group (also att.) has access. The appropriate resources can then be configured by search rules. (Further details on project tickets)
Not much to test so far on this end - I can demonstrate on dev, but this would allow us to show a (manual) end-to-end flow for feedback.
> feat(9): Create a public permission group and a lister

- coral/media/js/views/components/workflows/show-nodes.js
- coral/plugins/evaluation-meeting-workflow.json
- coral/settings.py
- coral/templates/views/components/workflows/show-nodes.htm
This pull request includes significant updates to the `show-nodes` component in the `coral` project, improving code readability, maintainability, and user interface presentation. The changes include refactoring the JavaScript view model, updating the HTML template, and adding a new title property to the workflow configuration.
Improvements to the `show-nodes` component:
* [`coral/media/js/views/components/workflows/show-nodes.js`](diffhunk://#diff-029db654f830d15074a5acbce525df35d620daff4306760894672e50204f924eL12-R60): Refactored the view model to use `self` for better readability and maintainability. Added a new method `parseConcept` to handle concept parsing and updated the `getORMData` method to utilize this new method.
User interface enhancements:
* …
> Feat/#2841 Fix Evaluation Meetings Detail Townland

- coral/plugins/heritage-asset-designation-workflow.json
- coral/settings.py
This will populate the designation letter templates with the owners name and address details if they are present.
The county node of the owner has been changed to a concept
- Reload Person model
- Coral Reload
- Create a person with an address
- Start a designation and set the owner as the person created
- Generate a letter
- The owner and address should populate at the top left of the letter
> Fix (Person) #2682: Letters Designation - Populate the owner name and address

- coral/media/js/viewmodels/workflow.js
- coral/templates/views/components/plugins/workflow.htm
This is the fix to apply node options when you hit back on the workflows.
This has been applied and tested on dev
> hotfix: apply nodeOptions on back and tab select

- coral/media/js/views/components/workflows/assign-consultation-workflow/related-heritage-asset-map.js
- coral/settings.py
Changes: 
Updated how we are accessing the geo-data from the json response 
Tests: 
Run `make webpack` to compile the javascript code for the fix to take effect 
- Navigate to the assign consultation workflow and add two or more related heritage assets with geo data 
- Skip to the map and enure that all the heritage assets appear on the map 
Testers:
@StuCM @OwenGalvia
> fix: #2982 fix error fetching geojson data

- coral/media/css/project.css
- coral/media/js/views/components/plugins/dashboard.js
- coral/settings.py
- coral/templates/views/components/cards/dashboard-card.htm
- coral/views/dashboard.py
- coral/views/dashboards/dashboard_utils.py
- coral/views/dashboards/planning_strategy.py
This updates the nodes showing for the planning cards on the dashboard
Consultation date has been removed
Description was removed
Heritage Asset Ref has been added
Assigned To has been added
Classification has been added
The sorting function has been updated to sort dates with time zones. This created an error as a knock on effect of updating the pagination rendering.
- Run a webpack
- Follow tests here [#2814](https://tree.taiga.io/project/viktoriabon-coral-phase-2/us/2814?milestone=433804)
> Fix: #2814 Planning Dashboard Updates

- coral/media/js/views/components/workflows/fmw-workflow/get-selected-monument-details.js
- coral/plugins/agriculture-and-forestry-consultation-workflow.json
- coral/plugins/curatorial-workflow.json
- coral/plugins/fmw-inspection-workflow.json
- coral/settings.py
- coral/templates/views/components/workflows/fmw-workflow/get-selected-monument-details.htm
The widget used to display information for selected Heritage Assets was not displaying the data due to an error being thrown in one of the API calls
**Related Issue:** None
---
Several changes proposed:
- Check for `typeId` when pulling the townland to allow for null values
- If null values set the text to None
- Allow for multiple HA References - IHR, SMR, Garden, HB
- Update the label depending on which ref is picked
- Change the selected node to a param to allow it to be used across workflows
- Change the search string to a param to allow it to be used across workflows
- Update the workflows  
---
If any database models have been modified, added, or removed, list them below:
---
List any new functions or methods added, along with a brief description of their purpose:
---
Describe any …
> Fix: Get Selected Monument Details

- coral/media/js/views/components/workflows/fmw-workflow/get-selected-monument-details.js
- coral/templates/views/components/workflows/fmw-workflow/get-selected-monument-details.htm
This fixes the HA display selector to allow multiple townlands and designations to be displayed
> Fix: allow multiple townlands and designations

- coral/pkg/graphs/resource_models/Consultation.json
Updated the concept for the proposed grade to the NIHED type
Switch list order for domain list of criteria and allowed many select
Fix nodegroup issue with consultation status
> Fix(Consultation): many select for criteria, update proposed grade concept

- coral/pkg/graphs/resource_models/Consultation.json
- coral/plugins/curatorial-workflow.json
- coral/plugins/fmw-inspection-workflow.json
Hides the role type and meta role types in the FMW sign off step
Hides Cur E, role type and meta role types in curatorial workflow sign off step
> Fix: Fmw curatorial hide role type

- coral/media/js/views/components/workflows/agriculture-and-forestry-consultation-workflow/update-deadline.js
- coral/pkg/graphs/resource_models/Consultation.json
- coral/plugins/agriculture-and-forestry-consultation-workflow.json
- coral/plugins/curatorial-workflow.json
- coral/plugins/fmw-inspection-workflow.json
Within deadline was refreshing without node options and changing to send papers (the original name)
Couldn't figure out how to get around it so created a new node and update the appropriate workflows
Also fixed the error if no date had been selected.
> Fix: Agri workflow - within deadline node

- coral/views/api_file.py
removed broken logic and replaced it with logs to check the request that makes it through
> debug: log the response

- coral/utils/user_role.py
- coral/views/dashboards/planning_strategy.py
---
- _Add a list of propsed changes_
---
---
---
---
- (Add workflows as needed)
---
- (Add reports as needed)
---
```
make run
make webpack
```
[List any tests that need to be run to verify the changes.]
- (Add tests as needed)
---
[Add any additional context, …
> Feat: 130 refactor planning dashboards

- coral/views/dashboards/dashboard_utils.py
- coral/views/dashboards/excavation_strategy.py
- coral/views/dashboards/planning_strategy.py
- requirements.txt
---
- _Add a list of propsed changes_
---
---
---
---
- (Add workflows as needed)
---
- (Add reports as needed)
---
```
make run
make webpack
```
[List any tests that need to be run to verify the changes.]
- (Add tests as needed)
---
[Add any additional context, …
> feat: 132 added domain values

- coral/permissions/casbin.py
There is a big memory spike when `get_restricted_ids` gets hit. This happens mostly on geospatial requests - in particular, the MVT endpoint. For instances with very large documents, this can be orders of magnitude larger than necessary, as only the IDs are needed. Instead of pulling back all fields, this now just pulls back IDs, which reduces the query to a manageable size.
However, this highlights a bigger legacy issue that we still search for restricted, rather than unrestricted instances, which in many use-cases (especially ours) are by far the majority. As such, it would be good to address this API with upstream, as there is a double-negative going on in the logic.
**Related Task:** [#3099](https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/3099)
---
- Make ES query only …
> Workaround for restricted ids

- coral/settings.py
- coral/utils/afc_number.py
Fixes the issue with the Agriculture Workflow that stops the number generator from working
---
- Creates a new local variable for the ID Pattern in the afc script
---
---
---
---
- (Add workflows as needed)
---
- (Add reports as needed)
---
```
make run
make webpack …
```
> Hotfix: Agriculture Number Generator

- coral/views/dashboards/planning_strategy.py
The initial fix was working effectively locally but in staging still caused the pod to fail. This changes how the counters are called. There are still some delays but the page is able to load
---
- Changes the get_counters function
- Remove the assigned to is null check for the HB HM Managers Users as this was not working
---
---
---
---
- …
> Hotfix: Dashboard Loading Issue 2

- .github/workflows/changelog.yml
- .github/workflows/update_changelog.sh
- changelogs/sprint_30.md
- coral/settings.py
---
- This is my proposed change from the first merge
- Another line for testing
---
---
- Hey I added some functions
- Here is another line
---
---
- (Add workflows as needed)
---
- (Add reports as needed)
---
```
make run
make webpack
```
[List any tests that need to be run to verify the …
> Merge TEST HEADING

- coral/settings.py
[Provide a brief description of the issue this PR addresses]
---
- Testing My Changes
---
- My Model Changes
---
---
- My Concept Changes
---
---
---
---
---
---
```
```
---
> test: v bump

- coral/settings.py
My description
---
- These are my changes
---
- My Model changes
---
---
- My Function Changes
---
---
---
---
---
---
```
```
---
> test v bump

- coral/settings.py
My Description
---
- My new changes from my pr
---
- I added a model
---
---
---
---
---
---
---
---
```
```
---
> v bump for test

- coral/settings.py
Try Again
---
- Another change
---
- This is a model change
---
---
---
---
---
---
---
---
```
```
---
> v bump test

- coral/media/css/project.css
- coral/templates/views/components/plugins/init-workflow.htm
- coral/templates/views/components/search/resource-type-filter.htm
- coral/templates/views/graph/function-manager.htm
Make the workflow init, filter drop down and function selection page scrollable
---
- Added scroll and height to filter type drop down
- Added flex wrap to the functions selection page
- Added height and scroll to the init workflow page
- Added custom css for scrollable and height utilities 
---
---
---
---
---
---
---
---
---
```
```
- …
> Fix: Scrollable Pages

- coral/settings.py
Adds settings for the Strict Transport Security to force the use of HTTPS
---
- Add settings for the STS for 1 year
---
---
---
---
---
---
---
---
---
```
```
---
> fix: add strict transport security settings

- CHANGELOG_uat-security-fixes.md
- coral/settings.py
- Update settings to add the google cloud bucket
- Add settings for the STS for 1 year
**fix: add google cloud csp headers for uat**
[728](https://github.com/flaxandteal/coral-arches/pull/728) by @StuCM
**fix: add strict transport security settings**
[729](https://github.com/flaxandteal/coral-arches/pull/729) by @StuCM
> Release: UAT security fixes

- coral/plugins/evaluation-meeting-workflow.json
- coral/views/orm.py
[Provide a brief description of the issue this PR addresses]
---
- [List the changes you're proposing]
- [Be specific and concise]
---
---
---
---
---
---
---
---
- _values_list no longer works as expected so had to pull nodes directly using the orm
---
```
make run
```
- Navigate to location details step in the evaluation meeting workflow and details should be populated as they exist 
--- …
> fix: updated orm view to look for location details nodes

- coral/media/js/views/components/workflows/file-template.js
- coral/templates/views/components/workflows/file-template.htm
When you hit generate on a letter, there is no indication that the process has started
---
- Add loading icon to the letter generate and disable the button when loading
---
---
---
---
---
---
---
---
---
```
```
- Navigate to a workflow with letter generation - Excavation Licence
- Select a drop down and click generate
- Should show a …
> feat: add loading icon when a letter is generating

- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-ihr-workflow.json
- coral/plugins/add-monument-workflow.json
- coral/plugins/heritage-asset-designation-workflow.json
A large amount of the "Many" select fields are incorrectly named
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2236
---
- [List the changes you're proposing]
- [Be specific and concise]
---
---
---
---
---
---
---
---
---
```
make run
make manage CMD="coral reload"
make webpack
```
- Check the included ticket above and follow …
> chore: updated field names for various many selects in various workflows

- coral/functions/update_report_classification_type.py
One of the functions was triggering on import causing a cardinality error
---
- Update the context if function to work correctly
---
---
---
---
---
---
---
---
---
```
```
---
> Fix: Context Update Statement

- coral/plugins/issue-report-workflow.json
[Provide a brief description of the issue this PR addresses]
---
- [List the changes you're proposing]
- [Be specific and concise]
---
---
---
---
---
---
---
---
---
```
```
---
> fix: disable cm ref node in issue report workflow

- coral/media/js/views/components/plugins/licensing-workflow.js
- coral/plugins/add-building-workflow.json
- coral/plugins/add-garden-workflow.json
- coral/plugins/add-ihr-workflow.json
- coral/plugins/add-monument-workflow.json
- coral/plugins/heritage-asset-designation-workflow.json
This pr updates the many tiles info box labels to be more appropriate 
https://tree.taiga.io/project/viktoriabon-coral-phase-2/issue/2236
---
- Update the many tile titles for all HA workflows
- Update the many tile titles for HA Designation
- Update the many tile titles for Licensing
---
---
---
---
---
---
---
---
---
```
make manage …
```
> fix: updated many select labels
